/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LogEntry { 'message' : string, 'timestamp' : bigint }
export interface Metrics {
  'totalVolume' : bigint,
  'healthPercent' : number,
  'activeIssues' : bigint,
}
export interface Transaction {
  'id' : string,
  'status' : string,
  'type' : string,
  'error' : [] | [string],
  'stage' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'addLog' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'clearOldData' : ActorMethod<[], undefined>,
  'getLogs' : ActorMethod<[], Array<LogEntry>>,
  'getMetrics' : ActorMethod<[], Metrics>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'updateTransaction' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];