/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'type' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
  'stage' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const LogEntry = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Metrics = IDL.Record({
  'totalVolume' : IDL.Nat,
  'healthPercent' : IDL.Float64,
  'activeIssues' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addLog' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'clearOldData' : IDL.Func([], [], []),
  'getLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getMetrics' : IDL.Func([], [Metrics], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'updateTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'type' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'stage' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const LogEntry = IDL.Record({ 'message' : IDL.Text, 'timestamp' : IDL.Int });
  const Metrics = IDL.Record({
    'totalVolume' : IDL.Nat,
    'healthPercent' : IDL.Float64,
    'activeIssues' : IDL.Nat,
  });
  
  return IDL.Service({
    'addLog' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'clearOldData' : IDL.Func([], [], []),
    'getLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getMetrics' : IDL.Func([], [Metrics], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'updateTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };